name: libnosr-rs CI

on:
  push:
    branches: [ main ]
    paths:
      - 'libnosr-rs/**'
      - '.github/workflows/libnosr-rs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'libnosr-rs/**'
      - '.github/workflows/libnosr-rs.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libnosr-rs
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Run tests
        run: cargo test --verbose

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libnosr-rs
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libnosr-rs
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      
      - name: Check formatting
        run: cargo fmt -- --check
